<!-- App Settings -->
<Project>
	<PropertyGroup>
		<!-- Default properties inherited by all projects. Projects can override. -->
		<RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<AnalysisMode>AllEnabledByDefault</AnalysisMode>
		<AnalysisLevel>latest</AnalysisLevel>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RollForward>LatestMajor</RollForward>
	</PropertyGroup>

	<PropertyGroup>
		<!-- Disable NuGet packaging by default. Projects can override. -->
		<IsPackable>disable</IsPackable>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
		<DebugSymbols>true</DebugSymbols>
		<DebugType>full</DebugType>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
		<DebugSymbols>true</DebugSymbols>
		<DebugType>portable</DebugType>
	</PropertyGroup>
</Project>